spring.application.name=CMJD-FINAL-APP
server.port=8080

spring.data.mongodb.uri=mongodb+srv://rasularathnayake2007_db_user:rasula2007@angshop-cluster.lfjrams.mongodb.net/?appName=Angshop-Cluster
spring.data.mongodb.database=CMJD-FINAL-APP
